apiVersion: v1
kind: Service
metadata:
  name: {{ include "application-service.fullname" . }}
  labels:
    {{- include "application-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: container-port
      protocol: {{ .Values.service.protocol }}
      name: service-port
  selector:
    {{- include "application-service.selectorLabels" . | nindent 4 }}
